### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by rafaeltoledo** [heitorcolangelo/kappuccino#68]
As the library releases updates quickly, sometimes I feel a bit unconfortable to update it sometimes, as I don't know if the update contains breaking changes or only bug fixes.

Some suggestions is to tag each release and add a changelog to Github's releases tab, or a simpler solution, just by adding a CHANGES.md file to the root folder.

**Comment by heitorcolangelo** [comment]
Nice suggestions! I'll start to make it clear what the update contains.

**Comment by heitorcolangelo** [comment]
Fixed! Thanks!
