### ISSUE TITLE
Check drawable in a TextView

### ISSUE THREAD

**Issue by heitorcolangelo** [heitorcolangelo/kappuccino#79]
It would be good if there's a feature that enables to check a drawable (start, top, bottom or end) of TextView

**Comment by RobertKeazor** [comment]
Has this been issue been completed ? If not I could take a stab at it

**Comment by heitorcolangelo** [comment]
Hi Robert!
Not yet, feel free to take it :+1: 
Thanks

**Comment by heitorcolangelo** [comment]
Added on release 1.1.0

**Comment by RobertKeazor** [comment]
Nice!
