### ISSUE TITLE
DeteKT or Ktlint

### ISSUE THREAD

**Issue by victorolinasc** [heitorcolangelo/kappuccino#91]
A nice addition to the project would be to have a more standardized code base following either detekt or ktlint. I think detekt is easier to integrate currently than ktlint but that is just my opinion.

**Comment by heitorcolangelo** [comment]
I'm more familiar with Ktlint, but it's ok to use DeteKT.
Feel free to integrate any of these to the project!
Thanks again!

**Comment by heitorcolangelo** [comment]
@victorolinasc 
I've opened a PR for this enhancement, can you please make a code review for me?
Thanks!
https://github.com/heitorcolangelo/kappuccino/pull/95

**Comment by heitorcolangelo** [comment]
@victorolinasc ?

**Comment by cs-victor-nascimento** [comment]
Let's stick with ktlint then :)
